grafana:
  enabled: true
  defaultDashboardsEnabled: true
  adminUser: admin
  adminPassword: admin
  service:
    type: NodePort
    nodePort: 30031
  ingress:
    enabled: true
    hosts:
      - grafana.localhost
prometheus:
  ingress:
    enabled: true
    hosts:
      - prometheus.localhost
  service:
    type: NodePort
    nodePort: 30090
  prometheusSpec:
    additionalScrapeConfigs:
      - job_name: 'pushgateway'
        honor_labels: true
        static_configs:
          - targets: [ 'pushgateway-service:9091' ]
            labels:
              pushgateway_instance: pushgateway
